Repository kubevirt/kubevirt-tutorial, pull requests merged in 2019-07, with the labels that each got.

#96 Change the VM name to match the screenshot
  labs/lab7/lab7.md
Labels: approved, lgtm, size/XS

#106 Adapt owners
  OWNERS
Labels: approved, lgtm, size/XS

#105 Added Tests to Kubevirt-Tutorials
  .gitignore
  Makefile
  README.md
  administrator/ansible/playbooks/kubernetes.yml
  administrator/ansible/roles/common/tasks/centos.yml
  administrator/ansible/roles/kubevirt/tasks/kubevirt.yml
  hack/README.md
  hack/build
  hack/test_lab
  hack/tests
  labs/lab000/lab000.md
  labs/lab001/RSA/kubevirt-tutorial
  labs/lab001/RSA/kubevirt-tutorial.pub
  labs/lab001/lab001.md
  labs/lab002/lab002.md
  labs/lab003/lab003.md
  labs/lab004/lab004.md
  labs/lab005/lab005.md
  labs/lab006/images/kwebui-01.png
  labs/lab006/images/kwebui-02.png
  labs/lab006/images/kwebui-03.png
  labs/lab006/images/kwebui-04.png
  labs/lab006/images/kwebui-05.png
  labs/lab006/images/kwebui-06.png
  labs/lab006/lab006.md
  labs/lab007/images/basic_settings.png
  labs/lab007/images/new_project.png
  labs/lab007/images/new_vm_wizard.png
  labs/lab007/images/overview.png
  labs/lab007/images/pod_overview.png
  labs/lab007/images/pods.png
  labs/lab007/images/start_vm.png
  labs/lab007/images/ui.png
  labs/lab007/images/vm_console.png
  labs/lab007/lab007.md
  labs/lab008/lab008.md
  labs/lab009/images/grafana-01.png
  labs/lab009/images/grafana-02.png
  labs/lab009/images/grafana-03.png
  labs/lab009/images/promui-01.png
  labs/lab009/images/promui-02.png
  labs/lab009/images/promui-03.png
  labs/lab009/lab009.md
  labs/lab010/lab010.md
Labels: approved, kind/enhancement, lgtm, size/XL

#107 Bug: Fixing link pointing to a bad URL
  labs/lab001/lab001.md
Labels: approved, kind/bug, lgtm, size/XS
