Repository kubevirt/kubevirt-tutorial, pull requests merged in 2019-06, with the labels that each got.

#93 Feat: Added OWNERS file in order to give prow details to manage PR approval
  OWNERS
Labels: size/S

#95 Fix links to point to the new repo location
  labs/lab1/lab1.md
  labs/lab9/lab9.md
Labels: size/XS

#98 lab 3: wait for ready condition on kubevirt CR
  labs/lab3/lab3.md
Labels: approved, lgtm, size/XS

#99 lab 3: use running condition on cdi CR
  labs/lab3/lab3.md
Labels: approved, lgtm, size/XS

#100 lab 3: removed UI mentions, fix small typo
  labs/lab3/lab3.md
Labels: approved, lgtm, size/XS

#101 Fix typos
  labs/lab5/lab5.md
Labels: approved, lgtm, size/XS

#103 Update to KubeVirt 0.18.1, CDI 0.19.3 and k8s 0.15
  administrator/ansible/playbooks/kubernetes.yml
  administrator/ansible/roles/kubevirt/files/cdi-operator-manifests/cdi-operator.yaml
  administrator/ansible/roles/kubevirt/files/kubevirt-operator-manifests/kubevirt-operator.yaml
  administrator/terraform/gcp/varfiles/containerdays-2019.tfvars
  labs/lab2/lab2.md
  labs/lab6/lab6.md
Labels: approved, size/S

#104 Fixed typo & Improved navigation
  labs/lab0/lab0.md
  labs/lab1/lab1.md
  labs/lab10/lab10.md
  labs/lab2/lab2.md
  labs/lab3/lab3.md
  labs/lab4/lab4.md
  labs/lab5/lab5.md
  labs/lab6/lab6.md
  labs/lab7/lab7.md
  labs/lab8/lab8.md
  labs/lab9/lab9.md
Labels: approved, lgtm, size/M
